// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: cxmcqnctgybzqffbriup

class SupabaseConfig {
  static const String supabaseUrl = 'https://cxmcqnctgybzqffbriup.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4bWNxbmN0Z3lienFmZmJyaXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjExOTUyNjEsImV4cCI6MjA3Njc3MTI2MX0.ff-pKEaXaM4HmVMqeTSh2IkwlxQQsBxqZIpUD7GXePE';
}
